#define RESET_STATE             (0)
#define ALWAYS                  (1)
#define ORIGINAL             (0x00) //
#define RED_LED              (0x01) // RED LED 0
#define GRN_LED              (0x40) // 6 GREEN LED
#define SW2                  (0x08) // 2.3 SW2
#define SW1                  (0x02) // 4.1 SW1
#define Time_Sequence_Rate         (50)
#define S1250 (1250/Time_Sequence_Rate) //
#define S1000 (1000/Time_Sequence_Rate) //
#define S750   (750/Time_Sequence_Rate) //
#define S500   (500/Time_Sequence_Rate) //
#define S250   (250/Time_Sequence_Rate) //
#define USE_GPIO (0x00) // GPIO
#define USE_SMCLK (0x01) // SMCLK
#define RIGHT_FORWARD_SPEED (TB3CCR1)
#define LEFT_FORWARD_SPEED (TB3CCR2)
#define RIGHT_REVERSE_SPEED (TB3CCR3)
#define LEFT_REVERSE_SPEED (TB3CCR4)
#define DEFAULT (10000)
#define TB0CCR0_INTERVAL (1638)
#define WHEEL_OFF (0)
#define WHEEL_PERIOD (40000)
#define FORWARD ('F')
#define ForwardSecPause ('J')
#define REVERSE ('B')
#define Clockwise ('C')
#define CounterClockwise ('E')
#define WAIT ('W')
#define ForwardPause ('P')
#define ReversePause ('Q')
#define ClockwisePause ('N')
#define CounterClockwisePause ('S')
#define STATE_ONE (1)
#define five_hundo (16384)
#define TB0CCR1_INTERVAL (1638)
#define TB0CCR2_INTERVAL (32768)
#define P4PUD (P4OUT)
#define displayUpdate (4)
#define LCDBlink (10)
#define debounceDelay (16)
#define START_FIND ('S')
#define ascii_offset (0x30)
#define thous (1000)
#define hund (100)
#define tens (10)
#define DONE ('D')
#define FIVE_SEC ('F')
#define RESET ('R')
#define ELEC_BRAKE ('E')
#define FIND_LINE ('W')
#define BEGINNING (0)
#define SMALL_RING_SIZE (16)
#define LARGE_RING_SIZE (64)
#define BRW_FIFT (4)
#define CTLW_FIFT (0x5551)
#define BRW_FOUR (17)
#define CTLW_FOUR (0x4A00)
#define RTRNFLG ('\r')
#define LINEFD ('\n')
#define OFFST ('O')
#define ONST ('N')
#define YES ('Y')
#define LEFT ('L')
#define RIGHT ('R')
#define ZERO (0)
#define TWENTY (20)
#define NINETYTIME (7)
#define FOHFIHTIME (4)
#define LEFTFOHFIH ('Q')
#define RIGHTFOHFIH ('E')
#define DISPSTAGE ('K')
#define IOT_FSpeedR (18000)
#define IOT_FSpeedL (20000)
#define IOT_RSpeedR (18000)
#define IOT_RSpeedL (20000)
#define IOT_TSpeedR (10000)
#define IOT_TSpeedL (10000)
#define LINEFIND ('P')
#define BLACK (400)
#define FOUND ('F')

extern int process_buffer[LARGE_RING_SIZE];
extern int pb_index;
